import './styles.css';
const API_BASE=import.meta.env.VITE_API_BASE_URL||'https://kisanlink-api-ksfw.onrender.com';
const TOKEN='kisanlink_token',USER='kisanlink_user',logo='/assets/kisanlink-logo.png';
const state={route:location.hash.slice(1)||'/login',user:null};
const token=()=>localStorage.getItem(TOKEN),auth=()=>!!token();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>v==null?'—':`₹${Number(v).toLocaleString('en-IN')}`;
const date=v=>v?new Date(v).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
const badge=t=>`<span class="badge">${esc(t)}</span>`;
function session(){try{state.user=JSON.parse(localStorage.getItem(USER)||'null')}catch{state.user=null}}
async function api(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};if(token())h.Authorization=`Bearer ${token()}`;const r=await fetch(API_BASE+path,{...opt,headers:h});const txt=await r.text();let d={};try{d=txt?JSON.parse(txt):{}}catch{d={detail:txt}}if(!r.ok)throw Error(d.detail||`API ${r.status}`);return d}
function go(r){if(!auth()&&!['/login','/signup'].includes(r))r='/login';state.route=r;location.hash=r;render()}
window.addEventListener('hashchange',()=>{state.route=location.hash.slice(1)||'/login';render()});
function header(a){return `<header class="topbar"><button class="brand" onclick="go('/dashboard')"><img class="logo-img" src="${logo}"/><div><div class="brand-name">KISANLINK ${badge('LIVE')}</div><div class="brand-sub">Connecting Farmers to Better Markets</div></div></button><div class="top-actions"><button class="icon-btn" onclick="go('/notifications')">🔔</button><button class="avatar-btn" onclick="go('/profile')"><img class="avatar" src="${logo}"/></button></div></header><div class="location">⌖ <strong>Authenticated</strong><span>• ${esc(a||'KISANLINK')}</span></div>`}
function bottom(a){return `<nav class="bottomnav">${[['/dashboard','⌂','Home'],['/prices','▦','Prices'],['/sell','↗','Sell'],['/buyers','♙','Buyers'],['/transactions','▤','Wallet']].map(x=>`<button class="navitem ${a===x[0]?'active':''}" onclick="go('${x[0]}')"><span>${x[1]}</span>${x[2]}</button>`).join('')}</nav>`}
function layout(c,a){return `<div class="app-shell">${header(a)}<main class="page">${c}</main>${bottom(a)}</div>`}
const loading=t=>`<section class="loading-card"><div class="spinner"></div><b>${t||'Loading live data…'}</b><span>Fetching from KisanLink backend</span></section>`;
const empty=t=>`<div class="empty"><b>No live records yet</b><span>${esc(t)}</span></div>`;
const failure=e=>`<section class="card error-card"><b>Live data unavailable</b><p>${esc(e.message||e)}</p><button class="small-btn dark" onclick="location.reload()">Retry</button></section>`;
function login(){return `<div class="app-shell auth-shell"><div class="login"><div class="login-head"><img class="login-logo" src="${logo}"/><div><h1>KisanLink</h1>${badge('SIH26132')}<p>Connecting Farmers to Better Markets</p></div></div><div class="role-tabs"><button class="role active">👨‍🌾 Kisan</button><button class="role">🏢 Buyer</button><button class="role">🌾 FPO</button></div><div class="auth-card"><div class="live-note">● LIVE ACCOUNT LOGIN<br><span>No demo credentials. Your account is checked against the KisanLink API.</span></div><label>MOBILE NUMBER OR KISAN ID</label><input id="mobile" class="input" inputmode="tel" placeholder="+91 XXXXX XXXXX"/><label>SECURITY PIN / PASSWORD</label><input id="password" class="input" type="password" placeholder="Enter password"/><button class="btn primary full" onclick="loginSubmit()">Login to Kisan Dashboard →</button><button class="btn light full" onclick="go('/signup')">Create New Account</button></div><div class="secure"><div>✓<strong>HTTPS</strong> API</div><div>🔒<strong>JWT</strong> Session</div><div>⌘<strong>Neon</strong> PostgreSQL</div></div><p class="login-foot">Login is required before entering the app.</p></div></div>`}
async function loginSubmit(){try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({mobile:document.querySelector('#mobile').value.trim(),password:document.querySelector('#password').value})});localStorage.setItem(TOKEN,d.access_token);if(d.user)localStorage.setItem(USER,JSON.stringify(d.user));go('/dashboard')}catch(e){alert(e.message)}}
function signup(){return `<div class="app-shell auth-shell"><div class="login"><div class="login-head"><img class="login-logo" src="${logo}"/><div><h1>Create Account</h1><p>Real KisanLink account</p></div></div><div class="auth-card"><label>FULL NAME</label><input id="su-name" class="input" placeholder="Your name"/><label>MOBILE</label><input id="su-mobile" class="input" inputmode="tel" placeholder="+91 XXXXX XXXXX"/><label>PASSWORD</label><input id="su-pass" class="input" type="password" placeholder="Create password"/><label>PROFILE</label><select id="su-role" class="input"><option value="farmer">Farmer</option><option value="buyer">Buyer</option><option value="fpo">FPO</option></select><button class="btn primary full" onclick="signupSubmit()">Create Account →</button><button class="btn light full" onclick="go('/login')">Back to Login</button></div></div></div>`}
async function signupSubmit(){try{const d=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name:document.querySelector('#su-name').value.trim(),mobile:document.querySelector('#su-mobile').value.trim(),password:document.querySelector('#su-pass').value,role:document.querySelector('#su-role').value})});localStorage.setItem(TOKEN,d.access_token);if(d.user)localStorage.setItem(USER,JSON.stringify(d.user));go('/dashboard')}catch(e){alert(e.message)}}
function dashboard(){return layout(`<span class="eyebrow">LIVE KISAN DASHBOARD</span><h1 class="title">Namaste, ${esc(state.user?.name||'Kisan')} Ji</h1><p class="subtitle">Real account data and backend insights only.</p><div id="dash">${loading()}</div>`,'/dashboard')}
async function dashboardData(){try{const[m,l,o]=await Promise.all([api('/api/market/prices'),api('/api/listings/my'),api('/api/offers/my')]);const active=l.filter(x=>x.status==='active');document.querySelector('#dash').innerHTML=`<div class="grid2"><div class="stat"><div class="label">Latest Modal Price</div><div class="value">${m[0]?money(m[0].modal_price):'—'}</div><div class="meta">${m[0]?esc(m[0].crop):'No feed configured'}</div></div><div class="stat"><div class="label">Active Listings</div><div class="value">${active.length}</div><div class="meta">PostgreSQL</div></div><div class="stat"><div class="label">Buyer Offers</div><div class="value">${o.length}</div><div class="meta">Your account</div></div><div class="stat"><div class="label">KYC</div><div class="value">${state.user?.kyc_verified?'Verified':'Pending'}</div></div></div><section class="section ai"><div class="row">${badge('LIVE MARKET INSIGHT')}<span class="mini">Updated ${date(m[0]?.updated_at)}</span></div><p>${m[0]?`Latest ${esc(m[0].crop)} at ${esc(m[0].mandi)}: ${money(m[0].modal_price)}. Source: ${esc(m[0].source||'backend')}.`:'No authorized market feed is configured. Connect e-NAM/APMC data to enable real-time insight.'}</p><div class="cta"><button class="btn mint" onclick="go('/prices')">View Live Prices</button><button class="btn light" onclick="go('/sell')">Sell Produce</button></div></section><section class="section"><div class="section-head"><div class="section-title">My Live Listings</div><button class="link" onclick="go('/sell')">+ New Lot</button></div>${active.length?active.map(x=>`<div class="list-card"><div class="row"><div><h4>${esc(x.crop)}</h4><p>${esc(x.quantity)} ${esc(x.unit)} • ${esc(x.quality||'')}</p></div>${badge(x.status)}</div><div class="row"><b class="price">${money(x.asking_price)}</b><span class="mini">${date(x.updated_at)}</span></div></div>`).join(''):empty('Create a listing to start receiving real offers.')}</section>`}catch(e){document.querySelector('#dash').innerHTML=failure(e)}}
function prices(){return layout(`<span class="eyebrow">LIVE MARKET API</span><h1 class="title">Mandi Market Prices</h1><p class="subtitle">No mock prices are rendered.</p><div class="search">⌕ <input id="price-search" placeholder="Search crop or mandi…" oninput="filterPrices()"/></div><div id="prices">${loading('Fetching authorized market data…')}</div>`,'/prices')}
async function priceData(){try{window.__prices=await api('/api/market/prices');filterPrices()}catch(e){document.querySelector('#prices').innerHTML=failure(e)}}
function filterPrices(){const q=(document.querySelector('#price-search')?.value||'').toLowerCase();const r=(window.__prices||[]).filter(x=>`${x.crop} ${x.mandi} ${x.variety||''}`.toLowerCase().includes(q));document.querySelector('#prices').innerHTML=r.length?r.map(x=>`<div class="list-card"><div class="row"><div><h4>${esc(x.crop)}</h4><p>${esc(x.mandi)} • ${esc(x.variety||'')}</p></div>${badge('LIVE')}</div><div class="row"><span class="price">${money(x.modal_price)}<small> / ${esc(x.unit||'qtl')}</small></span><span class="mini">Min ${money(x.min_price)} • Max ${money(x.max_price)}</span></div><p class="source-line">Source: ${esc(x.source||'KisanLink backend')} • Updated ${date(x.updated_at)}</p><button class="small-btn dark" onclick="go('/sell')">Sell at this market</button></div>`).join(''):empty('No live market record matches your search.')}
function sell(){return layout(`<span class="eyebrow">LIVE LISTING → POSTGRESQL</span><h1 class="title">Sell Your Produce</h1><p class="subtitle">Every submitted lot is linked to your account.</p><section class="card"><label>CROP</label><input id="s-crop" class="input" placeholder="Wheat"/><div class="grid2"><div><label>QUANTITY</label><input id="s-qty" class="input" type="number" min="0"/></div><div><label>UNIT</label><select id="s-unit" class="input"><option>qtl</option><option>kg</option><option>crate</option></select></div></div><div class="grid2"><div><label>QUALITY / GRADE</label><input id="s-quality" class="input" placeholder="Grade A"/></div><div><label>ASKING PRICE ₹</label><input id="s-price" class="input" type="number" min="0"/></div></div><label>DESCRIPTION</label><textarea id="s-desc" class="input" rows="4" placeholder="Variety, harvest, location…"></textarea><button class="btn primary full" onclick="createListing()">List Produce & Request Bids →</button></section><section id="my-listings" class="section">${loading()}</section>`,'/sell')}
async function createListing(){try{const b={crop:document.querySelector('#s-crop').value.trim(),quantity:Number(document.querySelector('#s-qty').value),unit:document.querySelector('#s-unit').value,quality:document.querySelector('#s-quality').value.trim(),asking_price:Number(document.querySelector('#s-price').value),description:document.querySelector('#s-desc').value.trim()};if(!b.crop||!b.quantity)return alert('Crop and quantity are required');await api('/api/listings',{method:'POST',body:JSON.stringify(b)});alert('Listing saved to PostgreSQL');loadMyListings()}catch(e){alert(e.message)}}
async function loadMyListings(){try{const r=await api('/api/listings/my');document.querySelector('#my-listings').innerHTML=`<div class="section-head"><div class="section-title">My Listings</div>${badge(`${r.length} total`)}</div>${r.length?r.map(x=>`<div class="list-card"><div class="row"><div><h4>${esc(x.crop)}</h4><p>${esc(x.quantity)} ${esc(x.unit)} • ${esc(x.quality||'')}</p></div>${badge(x.status)}</div><b class="price">${money(x.asking_price)}</b><p class="source-line">Created ${date(x.created_at)}</p></div>`).join(''):empty('No listings yet.')}`}catch(e){document.querySelector('#my-listings').innerHTML=failure(e)}}
function buyers(){return layout(`<span class="eyebrow">LIVE OFFERS</span><h1 class="title">Buyer Marketplace</h1><p class="subtitle">Only offers returned by the backend are shown.</p><div id="buyers">${loading()}</div>`,'/buyers')}
async function buyerData(){try{const r=await api('/api/offers/my');document.querySelector('#buyers').innerHTML=r.length?r.map(x=>`<div class="list-card"><div class="row"><div><h4>${esc(x.buyer_name||'Buyer')}</h4><p>${esc(x.crop||'Produce')} • ${date(x.created_at)}</p></div>${badge(x.status||'pending')}</div><div class="row"><span class="price">${money(x.price)}<small> / qtl</small></span><b>${esc(x.quantity||0)} qtl</b></div></div>`).join(''):empty('No real buyer offers are available for this account.') }catch(e){document.querySelector('#buyers').innerHTML=failure(e)}}
function transactions(){return layout(`<span class="eyebrow">REAL TRANSACTION LEDGER</span><h1 class="title">Transactions & Escrow Wallet</h1><p class="subtitle">No fabricated balance or settlement is shown.</p><div id="tx">${loading()}</div>`,'/transactions')}
async function txData(){try{const r=await api('/api/transactions/my');document.querySelector('#tx').innerHTML=r.length?r.map(x=>`<div class="list-card"><div class="row"><div><h4>${esc(x.type||'Transaction')}</h4><p>${esc(x.reference||'')} • ${date(x.created_at)}</p></div>${badge(x.status||'pending')}</div><span class="price">${money(x.amount)}</span><p class="source-line">${esc(x.payment_method||'')}</p></div>`).join(''):empty('No transactions yet. A real payment/settlement integration is required to populate this ledger.') }catch(e){document.querySelector('#tx').innerHTML=failure(e)}}
function notifications(){return layout(`<span class="eyebrow">ACCOUNT EVENTS</span><h1 class="title">Notifications</h1><div id="notes">${loading()}</div>`,'')}
async function noteData(){try{const r=await api('/api/notifications');document.querySelector('#notes').innerHTML=r.length?r.map(x=>`<div class="list-card"><div class="row"><h4>${esc(x.title||'Notification')}</h4>${badge(x.read?'Read':'New')}</div><p>${esc(x.message||'')}</p><span class="mini">${date(x.created_at)}</span></div>`).join(''):empty('No notifications yet.')}catch(e){document.querySelector('#notes').innerHTML=failure(e)}}
function profile(){return layout(`<span class="eyebrow">ACCOUNT</span><h1 class="title">My Profile</h1><section class="card profile-card"><img class="profile-logo" src="${logo}"><h2>${esc(state.user?.name||'User')}</h2><p>${esc(state.user?.mobile||'')}</p><div class="grid2"><div class="stat"><div class="label">Role</div><div class="value">${esc(state.user?.role||'')}</div></div><div class="stat"><div class="label">KYC</div><div class="value">${state.user?.kyc_verified?'Verified':'Pending'}</div></div></div><button class="btn light full" onclick="logout()">Logout</button></section>`,'')}
function logout(){localStorage.removeItem(TOKEN);localStorage.removeItem(USER);go('/login')}
async function render(){session();if(!auth()&&!['/login','/signup'].includes(state.route)){state.route='/login';location.hash='/login'}const root=document.querySelector('#app');if(state.route==='/login')root.innerHTML=login();else if(state.route==='/signup')root.innerHTML=signup();else if(state.route==='/dashboard'||state.route==='/'){root.innerHTML=dashboard();dashboardData()}else if(state.route==='/prices'){root.innerHTML=prices();priceData()}else if(state.route==='/sell'){root.innerHTML=sell();loadMyListings()}else if(state.route==='/buyers'){root.innerHTML=buyers();buyerData()}else if(state.route==='/transactions'){root.innerHTML=transactions();txData()}else if(state.route==='/notifications'){root.innerHTML=notifications();noteData()}else if(state.route==='/profile')root.innerHTML=profile();else root.innerHTML=login()}
Object.assign(window,{go,render,loginSubmit,signupSubmit,createListing,loadMyListings,filterPrices,logout});render();
