import './styles.css';

const API_BASE=import.meta.env.VITE_API_BASE_URL||'https://kisanlink-api-ksfw.onrender.com';
const TOKEN='kisanlink_token',USER='kisanlink_user',LOGO='/assets/kisanlink-logo.svg',FARMER='/farmer.webp';
const state={route:location.hash.slice(1)||'/login',user:null,location:null};
const token=()=>localStorage.getItem(TOKEN),auth=()=>!!token();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>v==null?'—':`₹${Number(v).toLocaleString('en-IN')}`;
const dt=v=>v?new Date(v).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
const badge=t=>`<span class="badge">${esc(t)}</span>`;
function session(){try{state.user=JSON.parse(localStorage.getItem(USER)||'null')}catch{state.user=null}}
async function api(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};if(token())h.Authorization=`Bearer ${token()}`;const r=await fetch(API_BASE+path,{...opt,headers:h});const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch{d={detail:text}}if(!r.ok)throw Error(d.detail||`API ${r.status}`);return d}
function go(r){if(!auth()&&!['/login','/signup'].includes(r))r='/login';state.route=r;location.hash=r;render();window.scrollTo(0,0)}
window.addEventListener('hashchange',()=>{state.route=location.hash.slice(1)||'/login';render()});
const loading=t=>`<section class="loading-card"><div class="spinner"></div><b>${t||'Loading live data…'}</b><span>Connected to KisanLink backend</span></section>`;
const empty=t=>`<div class="empty"><b>No live records</b><span>${esc(t)}</span></div>`;
const failure=e=>`<section class="card error-card"><b>Live data unavailable</b><p>${esc(e.message||e)}</p><button class="small-btn dark" onclick="location.reload()">Retry</button></section>`;
function header(active){return `<header class="topbar"><button class="brand" onclick="go('/dashboard')"><img class="logo-img" src="${LOGO}"/><div><div class="brand-name">KISANLINK ${badge('LIVE')}</div><div class="brand-sub">Connecting Farmers to Better Markets</div></div></button><div class="top-actions"><button class="icon-btn" onclick="go('/notifications')">🔔</button><button class="avatar-btn" onclick="go('/profile')"><img class="avatar" src="${FARMER}"/></button></div></header><div class="location">⌖ <strong>${esc(state.location?.label||state.user?.location||'Location not shared')}</strong><span>• ${esc(active||'KISANLINK')}</span></div>`}
function bottom(active){return `<nav class="bottomnav">${[['/dashboard','⌂','Home'],['/prices','↗','Prices'],['/sell','▤','Sell'],['/buyers','♙','Buyers'],['/transactions','▣','Wallet']].map(x=>`<button class="navitem ${active===x[0]?'active':''}" onclick="go('${x[0]}')"><span>${x[1]}</span>${x[2]}</button>`).join('')}</nav>`}
function layout(content,active){return `<div class="app-shell">${header(active)}<main class="page">${content}</main>${bottom(active)}</div>`}
function login(){return `<div class="app-shell auth-shell"><div class="login"><div class="login-head"><img class="login-logo" src="${LOGO}"/><div><h1>KisanLink</h1>${badge('SIH26132')}<p>Connecting Farmers to Better Markets</p></div></div><div class="role-tabs"><button class="role active">👨‍🌾 Kisan</button><button class="role">🏢 Buyer</button><button class="role">🌾 FPO</button></div><div class="auth-card"><div class="live-note">● LIVE ACCOUNT LOGIN<br/><span>No demo account. Login is checked against the real KisanLink API.</span></div><label>MOBILE NUMBER</label><input id="login-phone" class="input" inputmode="tel" placeholder="+91 XXXXX XXXXX"/><label>PASSWORD / SECURITY PIN</label><input id="login-pass" class="input" type="password" placeholder="Enter password"/><button class="btn primary full" onclick="loginSubmit()">Login to Kisan Dashboard →</button><button class="btn light full" onclick="go('/signup')">Create New Account</button></div><div class="secure"><div>✓<strong>HTTPS</strong> API</div><div>🔒<strong>JWT</strong> Session</div><div>⌘<strong>Neon</strong> PostgreSQL</div></div><p class="login-foot">You must login before entering KisanLink.</p></div></div>`}
async function loginSubmit(){try{const phone=document.querySelector('#login-phone').value.trim();const password=document.querySelector('#login-pass').value;const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({phone,password,role:'farmer'})});localStorage.setItem(TOKEN,d.access_token||d.token);localStorage.setItem(USER,JSON.stringify(d.user));state.user=d.user;go('/dashboard');await requestLocation()}catch(e){alert(e.message)}}
function signup(){return `<div class="app-shell auth-shell"><div class="login"><div class="login-head"><img class="login-logo" src="${LOGO}"/><div><h1>Create Account</h1><p>Real KisanLink account</p></div></div><div class="auth-card"><label>FULL NAME</label><input id="su-name" class="input" placeholder="Your name"/><label>MOBILE</label><input id="su-phone" class="input" inputmode="tel" placeholder="+91 XXXXX XXXXX"/><label>PASSWORD</label><input id="su-pass" class="input" type="password" placeholder="At least 6 characters"/><label>PROFILE</label><select id="su-role" class="input"><option value="farmer">Farmer</option><option value="buyer">Buyer</option><option value="fpo">FPO</option></select><button class="btn primary full" onclick="signupSubmit()">Create Real Account →</button><button class="btn light full" onclick="go('/login')">Back to Login</button></div></div></div>`}
async function signupSubmit(){try{const b={name:document.querySelector('#su-name').value.trim(),phone:document.querySelector('#su-phone').value.trim(),password:document.querySelector('#su-pass').value,role:document.querySelector('#su-role').value};const d=await api('/api/auth/register',{method:'POST',body:JSON.stringify(b)});localStorage.setItem(TOKEN,d.access_token||d.token);localStorage.setItem(USER,JSON.stringify(d.user));state.user=d.user;go('/dashboard');await requestLocation()}catch(e){alert(e.message)}}
async function requestLocation(){try{let p;if(window.Capacitor?.Plugins?.Geolocation)p=await window.Capacitor.Plugins.Geolocation.getCurrentPosition({enableHighAccuracy:true});else p=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true,timeout:10000}));const c=p.coords;state.location={lat:c.latitude,lon:c.longitude,label:`${c.latitude.toFixed(3)}, ${c.longitude.toFixed(3)}`};await api('/api/location',{method:'POST',body:JSON.stringify({latitude:c.latitude,longitude:c.longitude,label:state.location.label})});localStorage.setItem('kisanlink_location',JSON.stringify(state.location));render()}catch{state.location=null}}
function dashboard(){return layout(`<span class="eyebrow">LIVE KISAN DASHBOARD</span><h1 class="title">Namaste, ${esc(state.user?.name||'Kisan')} Ji</h1><p class="subtitle">Real account + real provider data only.</p><div id="dash">${loading()}</div>`,'/dashboard')}
async function dashboardData(){try{const [m,l,o,w]=await Promise.all([api('/api/market/prices'),api('/api/listings/my'),api('/api/offers/my'),state.location?api(`/api/weather?latitude=${state.location.lat}&longitude=${state.location.lon}`):Promise.resolve(null)]);const prices=m.prices||[],active=l.filter(x=>x.status==='active');const p=prices[0];document.querySelector('#dash').innerHTML=`<div class="grid2"><div class="stat"><div class="label">Latest Market Price</div><div class="value">${p?money(p.modal_price):'—'}</div><div class="meta">${p?esc(p.crop):'Live feed not configured'}</div></div><div class="stat"><div class="label">Active Listings</div><div class="value">${active.length}</div><div class="meta">Your PostgreSQL account</div></div><div class="stat"><div class="label">Buyer Offers</div><div class="value">${o.length}</div><div class="meta">Real backend offers</div></div><div class="stat"><div class="label">KYC</div><div class="value">${state.user?.kyc_verified?'Verified':'Pending'}</div><div class="meta">Provider integration required</div></div></div><section class="section ai"><div class="row">${badge('LIVE MARKET INSIGHT')}${badge(m.live?'AGMARKNET':'NOT CONNECTED')}</div><p>${p?`Latest ${esc(p.crop)} at ${esc(p.mandi)} is ${money(p.modal_price)}/qtl. Arrival date: ${esc(p.arrival_date||'—')}. This is the latest government-published observation, not a fabricated live quote.`:'Connect DATA_GOV_API_KEY on Render to show government market observations.'}</p><div class="cta"><button class="btn mint" onclick="go('/prices')">View Market Data</button><button class="btn light" onclick="go('/sell')">Sell Produce</button></div></section>${w?.current?`<section class="section card"><div class="section-head"><div class="section-title">Weather at Your Location</div>${badge('Open-Meteo')}</div><div class="grid2"><div class="stat"><div class="value">${esc(w.current.temperature_2m)}°C</div><div class="label">Temperature</div></div><div class="stat"><div class="value">${esc(w.current.precipitation)} mm</div><div class="label">Precipitation</div></div></div></section>`:''}<section class="section"><div class="section-head"><div class="section-title">My Active Lots</div><button class="link" onclick="go('/sell')">+ New Lot</button></div>${active.length?active.map(x=>`<div class="list-card"><div class="row"><div><h4>${esc(x.crop)}</h4><p>${esc(x.quantity)} ${esc(x.unit)} • ${esc(x.grade||'')}</p></div>${badge(x.status)}</div><div class="row"><b class="price">${money(x.asking_price)}</b><span class="mini">${dt(x.created_at)}</span></div></div>`).join(''):empty('Create your first real produce listing.')}</section>`}catch(e){document.querySelector('#dash').innerHTML=failure(e)}}
function prices(){return layout(`<span class="eyebrow">GOVERNMENT MARKET DATA</span><h1 class="title">Mandi Market Prices</h1><p class="subtitle">AGMARKNET/data.gov.in observations. No mock prices.</p><div class="search">⌕ <input id="price-q" placeholder="Search crop or mandi…" oninput="filterPrices()"/></div><div id="prices">${loading('Fetching market observations…')}</div>`,'/prices')}
async function priceData(){try{const d=await api('/api/market/prices?limit=100');window.__prices=d.prices||[];window.__market=d;filterPrices()}catch(e){document.querySelector('#prices').innerHTML=failure(e)}}
function filterPrices(){const el=document.querySelector('#prices');if(!el)return;const q=(document.querySelector('#price-q')?.value||'').toLowerCase();const r=(window.__prices||[]).filter(x=>`${x.crop} ${x.mandi} ${x.district} ${x.variety}`.toLowerCase().includes(q));el.innerHTML=window.__market?.live?`${r.length?r.map(x=>`<div class="list-card"><div class="row"><div><h4>${esc(x.crop)}</h4><p>${esc(x.mandi)} • ${esc(x.district||'')} • ${esc(x.variety||'')}</p></div>${badge(esc(x.arrival_date||'dated'))}</div><div class="row"><span class="price">${money(x.modal_price)}<small>/qtl</small></span><span class="mini">Min ${money(x.min_price)} • Max ${money(x.max_price)}</span></div><p class="source-line">AGMARKNET/data.gov.in • ${esc(x.arrival_date||'')}</p><button class="small-btn dark" onclick="go('/sell')">Sell This Crop</button></div>`).join(''):empty('No matching government observations.')}<div class="section card"><p class="mini">Market data is published daily; it should not be represented as a second-by-second quote.</p></div>`:empty('Government market feed is not configured. Add DATA_GOV_API_KEY in Render to enable it.')}
function sell(){return layout(`<span class="eyebrow">SELL • REAL LISTING</span><h1 class="title">Sell Your Produce</h1><p class="subtitle">Your lot is saved against your authenticated account.</p><section class="card"><label>CROP</label><input id="s-crop" class="input" placeholder="Wheat"/><div class="grid2"><div><label>QUANTITY</label><input id="s-qty" class="input" type="number" min="0"/></div><div><label>UNIT</label><select id="s-unit" class="input"><option>qtl</option><option>kg</option><option>crate</option></select></div></div><div class="grid2"><div><label>VARIETY</label><input id="s-variety" class="input" placeholder="Sharbati"/></div><div><label>GRADE</label><input id="s-grade" class="input" placeholder="Grade A"/></div></div><div class="grid2"><div><label>ASKING PRICE ₹</label><input id="s-price" class="input" type="number" min="0"/></div><div><label>MANDI</label><input id="s-mandi" class="input" placeholder="Indore APMC"/></div></div><button class="btn primary full" onclick="createListing()">List Produce & Request Real Bids →</button></section><section class="section card"><div class="section-head"><div class="section-title">Computer Vision</div>${badge('Provider-ready')}</div><input id="vision-file" class="input" type="file" accept="image/*"/><button class="btn light full" style="margin-top:8px" onclick="runVision()">Analyze Crop Image</button><div id="vision-result"></div><p class="mini">No fabricated grade is shown. A real CV model endpoint must be configured first.</p></section><section id="my-listings" class="section">${loading()}</section>`,'/sell')}
async function createListing(){try{const b={crop:document.querySelector('#s-crop').value.trim(),quantity:Number(document.querySelector('#s-qty').value),unit:document.querySelector('#s-unit').value,variety:document.querySelector('#s-variety').value.trim(),grade:document.querySelector('#s-grade').value.trim(),asking_price:Number(document.querySelector('#s-price').value)||null,mandi:document.querySelector('#s-mandi').value.trim()||null};if(!b.crop||!b.quantity)return alert('Crop and quantity are required');await api('/api/listings',{method:'POST',body:JSON.stringify(b)});alert('Real listing saved');loadMyListings()}catch(e){alert(e.message)}}
async function loadMyListings(){try{const r=await api('/api/listings/my');document.querySelector('#my-listings').innerHTML=`<div class="section-head"><div class="section-title">My Live Lots</div>${badge(`${r.length} total`)}</div>${r.length?r.map(x=>`<div class="list-card"><div class="row"><div><h4>${esc(x.crop)}</h4><p>${esc(x.quantity)} ${esc(x.unit)} • ${esc(x.variety||'')} • ${esc(x.grade||'')}</p></div>${badge(x.status)}</div><b class="price">${money(x.asking_price)}</b><p class="source-line">${esc(x.mandi||'Mandi not specified')} • ${dt(x.created_at)}</p></div>`).join(''):empty('No listings yet.')}`}catch(e){document.querySelector('#my-listings').innerHTML=failure(e)}}
async function runVision(){const f=document.querySelector('#vision-file').files[0];if(!f)return alert('Select a crop image first');const fd=new FormData();fd.append('file',f);try{const r=await fetch(API_BASE+'/api/vision/analyze',{method:'POST',headers:{Authorization:`Bearer ${token()}`},body:fd});const d=await r.json();if(!r.ok)throw Error(d.detail||'Vision provider unavailable');document.querySelector('#vision-result').innerHTML=`<div class="list-card"><b>Verified provider result</b><pre>${esc(JSON.stringify(d.result,null,2))}</pre></div>`}catch(e){document.querySelector('#vision-result').innerHTML=failure(e)}}
function buyers(){return layout(`<span class="eyebrow">BUYER MARKETPLACE</span><h1 class="title">Verified Buyer Offers</h1><p class="subtitle">Only database-backed offers appear here.</p><div id="buyers">${loading()}</div>`,'/buyers')}
async function buyerData(){try{const r=await api('/api/offers/my');document.querySelector('#buyers').innerHTML=r.length?r.map(x=>`<div class="list-card"><div class="row"><div><h4>${esc(x.buyer_name||'Buyer')}</h4><p>${esc(x.crop)} • ${esc(x.quantity)} ${esc(x.unit||'qtl')}</p></div>${badge(x.status)}</div><div class="row"><span class="price">${money(x.price)}<small>/qtl</small></span><span class="mini">${dt(x.created_at)}</span></div></div>`).join(''):empty('No real offers for your account yet. Buyer verification provider is not configured.') }catch(e){document.querySelector('#buyers').innerHTML=failure(e)}}
function fpo(){return layout(`<span class="eyebrow">FPO HUB</span><h1 class="title">FPO & Collective Hub</h1><p class="subtitle">Real FPO records require an authorized registry/data source.</p><section class="card">${empty('No FPO provider is configured. Add the authorized FPO registry/API details and credentials.')}</section><section class="section card"><b>Logistics</b><p class="mini">GPS position can be captured from the device. Route optimization, truck tracking and warehouse inventory require a logistics/warehouse provider.</p><button class="btn light full" onclick="requestLocation()">Use My Current Location</button></section>`,'/fpo')}
function transactions(){return layout(`<span class="eyebrow">TRANSACTIONS & ESCROW</span><h1 class="title">Wallet & Settlements</h1><p class="subtitle">Only real ledger records are displayed.</p><div id="tx">${loading()}</div><section class="section card"><b>Payment provider</b><p class="mini">Razorpay verification/webhook endpoints are ready, but live payments require your merchant credentials. DBT/bank settlement requires an authorized banking integration.</p></section>`,'/transactions')}
async function txData(){try{const r=await api('/api/transactions/my');document.querySelector('#tx').innerHTML=r.length?r.map(x=>`<div class="list-card"><div class="row"><div><h4>Transaction #${esc(x.id)}</h4><p>${esc(x.provider||'Ledger')} • ${dt(x.created_at)}</p></div>${badge(x.status)}</div><span class="price">${money(x.amount)}</span><p class="source-line">${esc(x.provider_ref||'No provider reference')}</p></div>`).join(''):empty('No settlements yet. No fake balance is shown.')}catch(e){document.querySelector('#tx').innerHTML=failure(e)}}
function notifications(){return layout(`<span class="eyebrow">ACCOUNT EVENTS</span><h1 class="title">Notifications</h1><div id="notes">${loading()}</div>`,'')}
async function noteData(){try{const r=await api('/api/notifications');document.querySelector('#notes').innerHTML=r.length?r.map(x=>`<div class="list-card"><div class="row"><h4>${esc(x.title)}</h4>${badge(x.read?'Read':'New')}</div><p>${esc(x.message)}</p><span class="mini">${dt(x.created_at)}</span></div>`).join(''):empty('No notifications yet.')}catch(e){document.querySelector('#notes').innerHTML=failure(e)}}
function profile(){return layout(`<span class="eyebrow">ACCOUNT</span><h1 class="title">My Profile</h1><section class="card profile-card"><img class="profile-logo" src="${LOGO}"><h2>${esc(state.user?.name||'User')}</h2><p>${esc(state.user?.phone||'')} • ${esc(state.user?.role||'farmer')}</p><p>${state.user?.kyc_verified?badge('KYC VERIFIED'):badge('KYC PENDING')}</p><button class="btn light full" onclick="requestLocation()">Share Current Location</button><button class="btn primary full" style="margin-top:8px" onclick="logout()">Logout</button></section>`,'')}
function logout(){localStorage.removeItem(TOKEN);localStorage.removeItem(USER);state.user=null;go('/login')}
async function render(){session();if(!auth()&&!['/login','/signup'].includes(state.route)){state.route='/login';location.hash='/login'}if(!state.location){try{state.location=JSON.parse(localStorage.getItem('kisanlink_location')||'null')}catch{}}const r=state.route;let html=r==='/login'?login():r==='/signup'?signup():r==='/dashboard'?dashboard():r==='/prices'?prices():r==='/sell'?sell():r==='/buyers'?buyers():r==='/fpo'?fpo():r==='/transactions'?transactions():r==='/notifications'?notifications():r==='/profile'?profile():login();document.getElementById('app').innerHTML=html;setTimeout(()=>{if(r==='/dashboard')dashboardData();if(r==='/prices')priceData();if(r==='/sell')loadMyListings();if(r==='/buyers')buyerData();if(r==='/transactions')txData();if(r==='/notifications')noteData()},0)}
window.go=go;window.loginSubmit=loginSubmit;window.signupSubmit=signupSubmit;window.createListing=createListing;window.loadMyListings=loadMyListings;window.runVision=runVision;window.requestLocation=requestLocation;window.logout=logout;window.render=render;render();
